services:
  db_local:
    build:
      context: ./
      dockerfile: ./docker_files/db_local/Dockerfile
    restart: always
    hostname: db_local
    environment:
      ME_CONFIG_REDIS_ADMINUSERNAME: admin
      ME_CONFIG_REDIS_ADMINPASSWORD: pass
      ME_CONFIG_REDIS_URL: redis://admin:pass@redislocal:6379/
    volumes:
      - ./src/db_local:/var/db_local

  api_local:
    build: 
      context: ./
      dockerfile: ./docker_files/api_local/Dockerfile
    volumes:
      - ./src/api_local:/usr/app
    ports:
      - 3000:3000
    environment:
      DB_HOST: db_local
      DB_PORT: 6379
      DB_USER: 'admin'
      DB_PASSWORD: 'abc123'
      DB_NAME: airlux_local_DB
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on:
      - db_local
   
  mqtt:
    build:
      context: ./
      dockerfile: ./docker_files/mosquitto/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883