services:
  db_local:
    build:
      context: ./
      dockerfile: ./docker_files/db_local/Dockerfile
    restart: always
    environment:
      ME_CONFIG_REDIS_ADMINUSERNAME: admin
      ME_CONFIG_REDIS_ADMINPASSWORD: pass
      ME_CONFIG_REDIS_URL: redis://admin:pass@redislocale:6379/
    volumes:
      - ./src/db_locale:/var/db_locale

  api_local:
    build: 
      context: ./
      dockerfile: ./docker_files/api_local/Dockerfile
    volumes:
      - ./src/api_local:/usr/app
    ports:
      - 3000:3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: patientsdb
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on:
      - db_local
    networks:
      - local_network

  mqtt:
    build:
      context: ./
      dockerfile: ./docker_files/mosquitto/Dockerfile
    ports:
      - 1883:1883
    volumes:
      - ./src/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - local_network

networks:
  local_network: