services:
  db_local:
    build:
      context: ./
      dockerfile: ./docker_files/db_local/Dockerfile
    restart: always
    environment:
      ME_CONFIG_REDIS_ADMINUSERNAME: admin
      ME_CONFIG_REDIS_ADMINPASSWORD: pass
      ME_CONFIG_REDIS_URL: redis://admin:pass@redislocal:6379/
    volumes:
      - ./src/db_local:/var/db_local

  api_local:
    build: 
      context: ./
      dockerfile: ./docker_files/api_local/Dockerfile
    volumes:
      - ./src/api_local:/usr/app
    ports:
      - 3000:3000
    environment:
      REDIS_DATABASE: airluxLocalDB
      REDIS_USER: admin
      REDIS_PASSWORD: abc123
      REDIS_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: redisdb
    depends_on:
      - db_local
    networks:
      - local_network

  mqtt:
    build:
      context: ./
      dockerfile: ./docker_files/mosquitto/Dockerfile
    ports:
      - 1883:1883
    volumes:
      - ./src/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - local_network

networks:
  local_network: