services:
  db_local:
    image: redis:bullseye
    restart: always
    hostname: db_local
    volumes:
      - ../db_local:/var/db_local
    ports:
      - 8306:6379
    networks:
      - local_network

  api_local:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/app/app
    ports:
      - 3030:3030
    environment:
      DB_HOST: db_local
      DB_PORT: 6379
      DB_PASSWORD: 'letmein'
      DB_NAME: airlux_local_DB
      DB_CLOUD_HOST: db_cloud
      DB_CLOUD_PORT: 3306
      DB_CLOUD_USER: 'admin'
      DB_CLOUD_PASSWORD: 'letmein'
      DB_CLOUD_NAME: airlux_cloud_db
      SERVER_PORT: 3030
    depends_on:
      - db_local
    networks:
      - local_network
      - cloud_network

  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ../mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883

networks:
  local_network:
  cloud_network:
