services:
  db_cloud:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db_cloud/initdb:/var/lib/mysql
      - ./src/db_cloud/initdb.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_DATABASE: airlux_cloud_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: db_cloud
    networks:
      - cloud_network

  api_cloud:
    build:
      context: ./
      dockerfile: ./docker_files/api_cloud/Dockerfile
    volumes:
      - ./src/api_cloud:/usr/app
    ports:
      - 3000:3000
    environment:
      DB_HOST: db_cloud
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: airlux_cloud_db
      DB_CONNECTION_LIMIT: 20
      SERVER_PORT: 3000
    depends_on:
      - db_cloud
    networks:
      - cloud_network

networks:
  cloud_network:


