services:
  db_distante:
    image: mysql
    #command: --authentication_policy=mysql_native_password
    #restart: unless-stopped
    volumes:
      - ./src/db_distante/initMysql:/var/lib/mysql
      #- ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./src/db_distante/initdb.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  api_distante:
    build: 
      context: ./
      dockerfile: ./docker_files/api_distante/Dockerfile
    volumes:
      - ./src/api_distante:/usr/app
    ports:
      - 3000:3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: patientsdb
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    depends_on:
      - db_distante
    networks:
      - internalnet

networks:
  internalnet:
