{
 "title": "MySQL metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mysql_global_status_uptime\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Open tables cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits[5m]) /\r\n(rate(mysql_global_status_table_open_cache_hits[5m]) + rate(mysql_global_status_table_open_cache_misses[5m])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffer Pool Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_read_requests / (mysql_global_status_innodb_buffer_pool_read_requests + mysql_global_status_innodb_buffer_pool_reads) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connexions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "command exec time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "mysql_global_status_command_exec_time",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}