services:
  pulsor:
    build:
      context: ./
      dockerfile: ./docker_files/pulsor/Dockerfile
    volumes:
      - ./src/pulsor:/var/pulsor

  validator:
    build: 
      context: ./
      dockerfile: ./docker_files/validator/Dockerfile
    restart: always
    volumes:
      - ./src/validator:/var/validator

  db_locale:
    build:
      context: ./
      dockerfile: ./docker_files/db_locale/Dockerfile
    restart: always
    environment:
      ME_CONFIG_REDIS_ADMINUSERNAME: admin
      ME_CONFIG_REDIS_ADMINPASSWORD: pass
      ME_CONFIG_REDIS_URL: redis://admin:pass@redislocale:6379/
    volumes:
      - ./src/db_locale:/var/db_locale 

  db_distante:
    build:
      context: ./
      dockerfile: ./docker_files/db_distante/Dockerfile
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      ME_CONFIG_MYSQL_ADMINUSERNAME: admin
      ME_CONFIG_MYSQL_ADMINPASSWORD: pass
      ME_CONFIG_MYSQL_URL: mysql://admin:pass@mysqldistante:3306/ 
    volumes:
      - ./src/db_distante:/var/lib/mysql
      
