FROM node:alpine

WORKDIR /usr/app
RUN npm install express
RUN npm install ip
RUN npm install dotenv
RUN npm install cors
RUN npm install pino
RUN npm install pino-pretty

CMD ["npm", "run", "airlux-local-db"]
#CMD ["npm" , "run"]
