services:
  validator:
    build: 
      context: ./
      dockerfile: ./docker_files/validator/Dockerfile
    restart: always
    volumes:
      - ./src/validator:/var/validator
    ports: 
      - 1883 # expose for mosquitto
      - 6379 # expose for redis
    networks:
      - local_local_network
      - cloud_cloud_network

networks:
  local_local_network:
    external: true
  cloud_cloud_network:
    external: true
