services:
  pulsor:
    build:
      context: ./
      dockerfile: ./docker_files/pulsor/Dockerfile
    volumes:
      - ./src/pulsor:/var/pulsor
    networks:
      - local_local-network

networks:
  local_local-network:
    external: true