global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql_exporter:9104']
    metrics_path: /metrics

remote_write:
  - url: localhost:3030
    basic_auth:
      username: admin
      password: letmein
