FROM mysql

#RUN apt-get update -y && \ 
#apt-get install nodejs -y && \ 
#apt-get install npm -y



#RUN apt-get update -y
#RUN apt-get upglsrade -y
#RUN apt-get install nodejs -y
##RUN apt-get update -y
#RUN apt-get upgrade -y
#RUN apt-get install curl -y
#RUN curl -OL https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb
#RUN dpkg -i mysql-apt-config*
#RUN apt update -y
#RUN apt install mysql-server -y
#RUN apt install wget
#RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb
#RUN apt-get install ./mysql-apt-config_0.8.22-1_all.deb
#RUN apt-get update
#RUN apt-get install mysql-server
#RUN apt-get -s install mariadb-server
#RUN apt-get install mysql-server -y
#RUN apt-get install npm -y
#CMD tail -f /dev/null
