version: '3'

services:
  zookeeper:
      image: zookeeper:3.7
      container_name: zookeeper
      ports:
        - "2181:2181"
      networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_MESSAGE_MAX_BYTES: 209715200
    depends_on:
      - zookeeper
    networks:
      - kafka_network

networks:
  kafka_network: