services:
  db_cloud:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../db_cloud/initdb:/var/lib/mysql
      - ../db_cloud/initdb.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_DATABASE: airlux_cloud_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: db_cloud
    networks:
      - cloud_network

  api_cloud:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/usr/app/app
    ports:
      - 3010:3010
    environment:
      DB_HOST: db_cloud
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: airlux_cloud_db
      DB_CONNECTION_LIMIT: 20
      SERVER_PORT: 3010
    depends_on:
      - db_cloud
    networks:
      - cloud_network

  grafana:
    image: grafana/grafana
    restart: always
    environment:
      GF_LOG_MODE: console file
      GF_LOG_FILE_PATH: /var/log/grafana/grafana.log
      GF_LOG_LEVEL: debug
    volumes:
      - ../grafana:/var/log/grafana
    ports:
      - 3000:3000
    networks:
      - cloud_network

networks:
  cloud_network:


