---
name: main

on:
  push:
    branches:
      - "setupPipelines"
    paths-ignore:
      - "**/README.md" # ignore README changes
  pull_request:
    paths-ignore:
      - "**/README.md" # ignore README changes

env:
  API_CLOUD_DIR: cloud/src/api_cloud
  API_LOCAL_DIR: local/src/api_local
  APPLICATION_DIR: app_airlux/test
  DOCUMENTATION_DIR: airlux
  ESP32_DIR: Arduino

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Determine which directories were changed
        id: changed_files
        run: |
          export CHANGED_FILES="$(git diff --name-only origin/main..origin/setupPipelines)"
          echo "Changed files: $CHANGED_FILES"

      - name: Lint and test API Cloud
        if: ${{ contains(env.CHANGED_FILES, env.API_CLOUD_DIR) }}
        run: |
          cd ${{ env.API_CLOUD_DIR }}
          npm ci
          npm run lint
          npm run test
